name: publish SG.NullableExtensions to nuget
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "src/**"
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.104
      - name: Pack
        run: dotnet pack -c Release src/SG.NullableExtensions
      - name: Publish
        run: dotnet nuget push ./package/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
